using UnityEngine;

public class CameraFollow : MonoBehaviour
{
    [SerializeField] private Transform _target = null;
    
    private Vector3 _offset = Vector3.zero; //Indica la separaci칩n entre el personaje y la c치mara. Siempre mantedr치 la misma separaci칩n inicial.
    private float _smoothing = 5.0f;

    private void Awake()
    {
        InitializeOffset();
    }

    private void FixedUpdate()
    {
        SmoothFollowTarget();
    }

    private void InitializeOffset()
    {
        _offset = transform.position - _target.position;
    }

    private void SmoothFollowTarget()
    {
        Vector3 targetCameraPosition = _target.position + _offset;
        transform.position = Vector3.Lerp(transform.position, targetCameraPosition, _smoothing * Time.fixedDeltaTime);
    }
}